services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8000:8000"
    env_file: .env
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
