services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - STABILITY_API_KEY=${STABILITY_API_KEY}
    env_file: .env

volumes: {}