services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - STABILITY_API_KEY=${STABILITY_API_KEY}

volumes: {}