FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY server/ ./server/

# Si usas variables de entorno, copia también .env si lo necesitas
COPY .env .

#CMD ["python"]