services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - FAL_API_KEY=${FAL_API_KEY}
    env_file: .env
    # depends_on:
    #   - libretranslate
    # dns:
    #   - 8.8.8.8
    #   - 1.1.1.1
    # dns_search: .
    networks:
      - app-net

  # libretranslate:
  #   image: libretranslate/libretranslate
  #   container_name: libretranslate
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - PORT=5000
  #   command: ["--load-only", "en,es"]
  #   restart: on-failure
  #   dns_search: .
  #   networks:
  #     - app-net

networks:
  app-net:
    driver: bridge
