version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
    env_file: .env
    depends_on:
      - libretranslate
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - app-net  # 👈 Añadido

  libretranslate:
    image: libretranslate/libretranslate
    container_name: libretranslate
    expose:
      - "5000"
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - app-net  # 👈 Añadido

networks:
  app-net:
    driver: bridge
